<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit697b0a7352d97971b1ef5675a4b82f09
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Base32\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Base32\\' => 
        array (
            0 => __DIR__ . '/..' . '/christian-riesen/base32/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit697b0a7352d97971b1ef5675a4b82f09::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit697b0a7352d97971b1ef5675a4b82f09::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit697b0a7352d97971b1ef5675a4b82f09::$classMap;

        }, null, ClassLoader::class);
    }
}
