<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf89d66a862a5b5fdfd49d30cd584af8f
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'StephenHill\\Benchmarks\\' => 23,
            'StephenHill\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'StephenHill\\Benchmarks\\' => 
        array (
            0 => __DIR__ . '/..' . '/stephenhill/base58/benchmarks',
        ),
        'StephenHill\\' => 
        array (
            0 => __DIR__ . '/..' . '/stephenhill/base58/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf89d66a862a5b5fdfd49d30cd584af8f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf89d66a862a5b5fdfd49d30cd584af8f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf89d66a862a5b5fdfd49d30cd584af8f::$classMap;

        }, null, ClassLoader::class);
    }
}
