<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Base32\\' => array($vendorDir . '/christian-riesen/base32/src'),
);
